In [1]:
import tensorflow as tf
import tensorflow_hub as hub
detector =hub.load("https://kaggle.com/models/tensorflow/faster-rcnn-inception-resnet-v2/frameworks/TensorFlow2/variations/640x640/versions/1")

In [12]:
img = tf.io.read_file('/content/images.jpeg')
img = tf.image.decode_jpeg(img,channels=3)
c_img = tf.image.convert_image_dtype(img,tf.float32)
img = tf.expand_dims(c_img,axis=0)

In [16]:
results = detector(img.numpy())

In [36]:
results

{'detection_multiclass_scores': <tf.Tensor: shape=(1, 100, 91), dtype=float32, numpy=
 array([[[9.99954641e-01, 4.52755121e-05, 2.71786039e-13, ...,
          5.49042496e-18, 6.82179315e-19, 9.32056632e-16],
         [9.99959052e-01, 4.09215354e-05, 4.24518979e-15, ...,
          1.14989406e-20, 2.43169545e-23, 3.27172370e-19],
         [9.99962509e-01, 3.73945986e-05, 3.07224217e-13, ...,
          1.10602975e-16, 1.35924088e-17, 6.70538793e-14],
         ...,
         [9.99998748e-01, 1.06489608e-06, 1.46182058e-16, ...,
          8.12113180e-23, 3.02579054e-23, 1.83410571e-18],
         [9.99987423e-01, 7.38411501e-08, 1.10383475e-07, ...,
          9.99780814e-10, 2.46176715e-08, 2.91381951e-07],
         [9.99987423e-01, 7.38411501e-08, 1.10383475e-07, ...,
          9.99780814e-10, 2.46176715e-08, 2.91381951e-07]]], dtype=float32)>,
 'raw_detection_boxes': <tf.Tensor: shape=(1, 300, 4), dtype=float32, numpy=
 array([[[0.26423544, 0.2104545 , 0.9306699 , 0.947775  ],
         [0.3